/* eslint-disable import/prefer-default-export */

export const lettersToSemaphore = {
  '\b': ['NW', 'SE'],
  '#': ['N', 'NE'],
  A: ['S', 'SW'],
  B: ['W', 'S'],
  C: ['S', 'NW'],
  D: ['N', 'S'],
  E: ['S', 'NE'],
  F: ['E', 'S'],
  G: ['S', 'SE'],
  H: ['W', 'SW'],
  I: ['NW', 'SW'],
  J: ['N', 'E'],
  K: ['N', 'SW'],
  L: ['NE', 'SW'],
  M: ['E', 'SW'],
  N: ['SE', 'SW'],
  O: ['W', 'NW'],
  P: ['W', 'N'],
  Q: ['W', 'NE'],
  R: ['W', 'E'],
  S: ['W', 'SE'],
  T: ['N', 'NW'],
  U: ['NW', 'NE'],
  V: ['N', 'SE'],
  W: ['E', 'NE'],
  X: ['NE', 'SE'],
  Y: ['E', 'NW'],
  Z: ['E', 'SE'],
};
